branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
      enforce_admins: false
      required_status_checks:
        strict: false
        contexts: []
      restrictions: null
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false