# site configuration
site_name: pangadfs
site_url: https://sansbacon.github.io/pangadfs/
site_description: pandas-based lineup optimization framework
site_author: Eric Truett
repo_url: https://github.com/sansbacon/pangadfs

theme:
  name: material

plugins:
  - search
  - mkdocstrings

markdown_extensions:
- toc:
    permalink: true
- admonition
- codehilite
- extra
- pymdownx.superfences
- pymdownx.tabbed

nav:
- pangadfs: index.md
- history-design-future.md
- features.md
- Developing pangadfs apps and plugins:
    - building-apps.md
    - plugin-namespaces.md
    - default-plugins.md
    - building-plugins.md
    - contributing.md
- release-notes.md
- Code Reference:
    - base: base-reference.md
    - crossover: crossover-reference.md
    - fitness: fitness-reference.md
    - misc: misc-reference.md
    - mutate: mutate-reference.md
    - optimize: optimize-reference.md
    - penalty: penalty-reference.md
    - pool: pool-reference.md
    - populate: populate-reference.md
    - pospool: pospool-reference.md
    - select: select-reference.md
    - validate: validate-reference.md
