# site configuration
site_name: pangadfs

theme:
  name: material

plugins:
  - search
  - mkdocstrings

nav:
    - Home: index.md
    - Code Reference:
        - default: default-reference.md
        - ga: ga-reference.md
        - base: base-reference.md
