# site configuration
site_name: pangadfs

theme:
  name: material

plugins:
  - search
  - mkdocstrings

nav:
    - Home: index.md
    - About: about.md
    - Plugin Namespaces: plugin-namespaces.md
    - Default Plugins: default-plugins.md
    - Building Apps with pangadfs: building-apps.md
    - Code Reference:
        - base: base-reference.md
        - crossover: crossover-reference.md
        - fitness: fitness-reference.md
        - misc: misc-reference.md
        - mutate: mutate-reference.md
        - penalty: penalty-reference.md
        - pool: pool-reference.md
        - populate: populate-reference.md
        - pospool: pospool-reference.md
        - postprocess: postprocess-reference.md
        - select: select-reference.md
        - validate: validate-reference.md
