# site configuration
site_name: pangadfs

theme:
  name: material

plugins:
  - search
  - mkdocstrings

nav:
    - Home: index.md
    - About: about.md
    - Plugin Namespaces: plugin-namespaces.md
    - Default Plugins: default-plugins.md
    - Building Apps with pangadfs: building-apps.md
    - Code Reference:
        - default: default-reference.md
        - ga: ga-reference.md
        - base: base-reference.md
